[project]
name = "jx-migrate"
version = "0.1.0"
description = "Automates migrating JinjaX templates to Jx"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=9.0.2",
    "ruff>=0.15.0",
]
